export const HEADER_MENU = [
    {
        id: 1,
        to: '/danh-sach/phim-bo',
        title: 'Phim Bộ',
    },
    {
        id: 2,
        to: '/danh-sach/phim-le',
        title: 'Phim Lẻ',
    },
    {
        id: 3,
        to: '/danh-sach/hoat-hinh',
        title: 'Hoạt Hình',
    },
    {
        id: 4,
        title: 'Thể loại',
        subMenu: [
            {
                id: 400,
                type: 'category',
                to: '/the-loai/hanh-dong',
                title: 'Hành Động',
            },
            {
                id: 401,
                type: 'category',
                to: '/the-loai/tinh-cam',
                title: 'Tình Cảm',
            },
            {
                id: 402,
                type: 'category',
                to: '/the-loai/hai-huoc',
                title: 'Hài Hước',
            },
            {
                id: 403,
                type: 'category',
                to: '/the-loai/co-trang',
                title: 'Cổ Trang',
            },
            {
                id: 404,
                type: 'category',
                to: '/the-loai/tam-ly',
                title: 'Tâm Lý',
            },
            {
                id: 405,
                type: 'category',
                to: '/the-loai/hinh-su',
                title: 'Hình Sự',
            },
            {
                id: 406,
                type: 'category',
                to: '/the-loai/chien-tranh',
                title: 'Thể Thao',
            },
            {
                id: 407,
                type: 'category',
                to: '/the-loai/the-thao',
                title: 'Thể Thao',
            },
            {
                id: 408,
                type: 'category',
                to: '/the-loai/vo-thuat',
                title: 'Võ Thuật',
            },
            {
                id: 409,
                type: 'category',
                to: '/the-loai/vien-tuong',
                title: 'Viễn Tưởng',
            },
            {
                id: 410,
                type: 'category',
                to: '/the-loai/phieu-luu',
                title: 'Phiêu Lưu',
            },
            {
                id: 411,
                type: 'category',
                to: '/the-loai/khoa-hoc',
                title: 'Khoa Học',
            },
            {
                id: 412,
                type: 'category',
                to: '/the-loai/kinh-di',
                title: 'Kinh Dị',
            },
            {
                id: 413,
                type: 'category',
                to: '/the-loai/am-nhac',
                title: 'Âm Nhạc',
            },
            {
                id: 414,
                type: 'category',
                to: '/the-loai/than-thoai',
                title: 'Thần Thoại',
            },
            {
                id: 415,
                type: 'category',
                to: '/the-loai/tai-lieu',
                title: 'Tài Liệu',
            },
            {
                id: 416,
                type: 'category',
                to: '/the-loai/gia-dinh',
                title: 'Gia Đình',
            },
            {
                id: 417,
                type: 'category',
                to: '/the-loai/chinh-kich',
                title: 'Chính Kịch',
            },
            {
                id: 418,
                type: 'category',
                to: '/the-loai/bi-an',
                title: 'Bí Ẩn',
            },
            {
                id: 419,
                type: 'category',
                to: '/the-loai/hoc-duong',
                title: 'Học Đường',
            },
            {
                id: 420,
                type: 'category',
                to: '/the-loai/kinh-dien',
                title: 'Kinh Điển',
            },
        ],
    },
    {
        id: 5,
        title: 'Quốc Gia',
        subMenu: [
            {
                id: 500,
                type: 'nation',
                to: '/quoc-gia/trung-quoc',
                title: 'Trung Quốc',
            },
            {
                id: 501,
                type: 'nation',
                to: '/quoc-gia/han-quoc',
                title: 'Hàn Quốc',
            },
            {
                id: 502,
                type: 'nation',
                to: '/quoc-gia/nhat-ban',
                title: 'Nhật Bản',
            },
            {
                id: 503,
                type: 'nation',
                to: '/quoc-gia/thai-lan',
                title: 'Thái Lan',
            },
            {
                id: 504,
                type: 'nation',
                to: '/quoc-gia/au-my',
                title: 'Âu Mỹ',
            },
            {
                id: 505,
                type: 'nation',
                to: '/quoc-gia/dai-loan',
                title: 'Đài Loan',
            },
            {
                id: 506,
                type: 'nation',
                to: '/quoc-gia/hong-kong',
                title: 'Hồng Kông',
            },
            {
                id: 507,
                type: 'nation',
                to: '/quoc-gia/an-do',
                title: 'Ấn Độ',
            },
            {
                id: 508,
                type: 'nation',
                to: '/quoc-gia/anh',
                title: 'Anh',
            },
            {
                id: 509,
                type: 'nation',
                to: '/quoc-gia/phap',
                title: 'Pháp',
            },
            {
                id: 510,
                type: 'nation',
                to: '/quoc-gia/canada',
                title: 'Canada',
            },
            {
                id: 511,
                type: 'nation',
                to: '/quoc-gia/duc',
                title: 'Đức',
            },
            {
                id: 512,
                type: 'nation',
                to: '/quoc-gia/tay-ban-nha',
                title: 'Tây Ban Nha',
            },
            {
                id: 513,
                type: 'nation',
                to: '/quoc-gia/tho-nhi-ky',
                title: 'Thổ Nhĩ Kỳ',
            },
            {
                id: 514,
                type: 'nation',
                to: '/quoc-gia/ha-lan',
                title: 'Hà Lan',
            },
            {
                id: 515,
                type: 'nation',
                to: '/quoc-gia/indonesia',
                title: 'Indonesia',
            },
            {
                id: 516,
                type: 'nation',
                to: '/quoc-gia/nga',
                title: 'Nga',
            },
            {
                id: 517,
                type: 'nation',
                to: '/quoc-gia/mexico',
                title: 'Mexico',
            },
            {
                id: 518,
                type: 'nation',
                to: '/quoc-gia/ba-lan',
                title: 'Ba Lan',
            },
            {
                id: 519,
                type: 'nation',
                to: '/quoc-gia/uc',
                title: 'Úc',
            },
            {
                id: 520,
                type: 'nation',
                to: '/quoc-gia/phap',
                title: 'Pháp',
            },
            {
                id: 521,
                type: 'nation',
                to: '/quoc-gia/thuy-dien',
                title: 'Thụy Điển',
            },
            //ll
            {
                id: 522,
                type: 'nation',
                to: '/quoc-gia/malaysia',
                title: 'Malaysia',
            },
            {
                id: 523,
                type: 'nation',
                to: '/quoc-gia/brazil',
                title: 'Brazil',
            },
            {
                id: 524,
                type: 'nation',
                to: '/quoc-gia/philippines',
                title: 'Philippines',
            },
            {
                id: 525,
                type: 'nation',
                to: '/quoc-gia/bo-dao-nha',
                title: 'Bồ Đào Nha',
            },
            {
                id: 526,
                type: 'nation',
                to: '/quoc-gia/y',
                title: 'Ý',
            },
            {
                id: 527,
                type: 'nation',
                to: '/quoc-gia/dan-mach',
                title: 'Đan Mạch',
            },
            {
                id: 528,
                type: 'nation',
                to: '/quoc-gia/uae',
                title: 'UAE',
            },
            {
                id: 529,
                type: 'nation',
                to: '/quoc-gia/na-uy',
                title: 'Na Uy',
            },
            {
                id: 530,
                type: 'nation',
                to: '/quoc-gia/thuy-si',
                title: 'Thụy Sỹ',
            },
            {
                id: 531,
                type: 'nation',
                to: '/quoc-gia/chau-phi',
                title: 'Châu Phi',
            },
            {
                id: 532,
                type: 'nation',
                to: '/quoc-gia/nam-phi',
                title: 'Nam Phi',
            },
            {
                id: 533,
                type: 'nation',
                to: '/quoc-gia/ukraina',
                title: 'Ukraina',
            },
            {
                id: 534,
                type: 'nation',
                to: '/quoc-gia/a-rap-xe-ut',
                title: 'Ả Rập Xê Út',
            },
            {
                id: 535,
                type: 'nation',
                to: '/quoc-gia/quoc-gia-khac',
                title: 'Quốc Gia Khác',
            },
        ],
    },
    {
        id: 6,
        to: '/danh-sach/tat-ca',
        title: 'Tất Cả',
    },
];

export const HEADER_LOG_ = [
    {
        id: 1,
        title: 'Đăng ký',
    },
    {
        id: 2,
        title: 'Đăng Nhập',
    },
];
